"""add inspection lifecycle fields

Revision ID: 0bcdec646194
Revises: af04a0ed4700
Create Date: 2026-09-12 13:50:26.945424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcdec646194'
down_revision: Union[str, Sequence[str], None] = 'af04a0ed4700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_runs', sa.Column('error_code', sa.String(length=100), nullable=True))
    op.add_column('inspection_runs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('inspection_runs', sa.Column('failed_stage', sa.String(length=50), nullable=True))
    op.add_column('inspection_runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('inspection_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_runs', 'completed_at')
    op.drop_column('inspection_runs', 'started_at')
    op.drop_column('inspection_runs', 'failed_stage')
    op.drop_column('inspection_runs', 'error_message')
    op.drop_column('inspection_runs', 'error_code')
    # ### end Alembic commands ###
