"""create inspection tables

Revision ID: ab95596d9f96
Revises: 
Create Date: 2026-09-10 15:21:29.156576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab95596d9f96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('x2', sa.Integer(), nullable=False),
    sa.Column('y2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_detections_inspection_id'), 'inspection_detections', ['inspection_id'], unique=False)
    op.create_table('inspection_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('ocr_status', sa.String(length=30), nullable=False),
    sa.Column('source_detections', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_fields_inspection_id'), 'inspection_fields', ['inspection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_fields_inspection_id'), table_name='inspection_fields')
    op.drop_table('inspection_fields')
    op.drop_index(op.f('ix_inspection_detections_inspection_id'), table_name='inspection_detections')
    op.drop_table('inspection_detections')
    op.drop_table('inspection_runs')
    # ### end Alembic commands ###
