"""add inspection stage statuses

Revision ID: af04a0ed4700
Revises: ab95596d9f96
Create Date: 2026-09-10 16:48:48.827249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af04a0ed4700'
down_revision: Union[str, Sequence[str], None] = 'ab95596d9f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_runs', sa.Column('segmentation_status', sa.String(length=30), nullable=False, server_default="unknown",),)
    op.add_column('inspection_runs', sa.Column('detection_status', sa.String(length=30), nullable=False, server_default="unknown",),)
    op.alter_column('inspection_runs', "segmentation_status", server_default=None,)
    op.alter_column('inspection_runs', "detection_status", server_default=None,)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_runs', 'detection_status')
    op.drop_column('inspection_runs', 'segmentation_status')
    # ### end Alembic commands ###
